/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pboproject;

/**
 *
 * @author Muhammad Hafidz A
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        adminMenu = new javax.swing.JMenu();
        addAdminMenu = new javax.swing.JMenuItem();
        removeAdminMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        dataMenu = new javax.swing.JMenu();
        addStudentMenu = new javax.swing.JMenuItem();
        removeStudentMenu = new javax.swing.JMenuItem();
        updateDataMenu = new javax.swing.JMenuItem();
        selectDataMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminMenu.setText("Admin");

        addAdminMenu.setText("Tambah Admin");
        adminMenu.add(addAdminMenu);

        removeAdminMenu.setText("Hapus Admin");
        adminMenu.add(removeAdminMenu);

        exitMenu.setText("Keluar");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        adminMenu.add(exitMenu);

        jMenuBar1.add(adminMenu);

        dataMenu.setText("Data Mahasiswa");

        addStudentMenu.setText("Tambah Data");
        dataMenu.add(addStudentMenu);

        removeStudentMenu.setText("Hapus Data");
        dataMenu.add(removeStudentMenu);

        updateDataMenu.setText("Perbarui Data");
        dataMenu.add(updateDataMenu);

        selectDataMenu.setText("Lihat Data");
        dataMenu.add(selectDataMenu);

        jMenuBar1.add(dataMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAdminMenu;
    private javax.swing.JMenuItem addStudentMenu;
    private javax.swing.JMenu adminMenu;
    private javax.swing.JMenu dataMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem removeAdminMenu;
    private javax.swing.JMenuItem removeStudentMenu;
    private javax.swing.JMenuItem selectDataMenu;
    private javax.swing.JMenuItem updateDataMenu;
    // End of variables declaration//GEN-END:variables
}
